#
# Copyright (c) 2022 ZettaScale Technology
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0, or the Apache License, Version 2.0
# which is available at https://www.apache.org/licenses/LICENSE-2.0.
#
# SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
#
# Contributors:
#   ZettaScale Zenoh Team, <zenoh@zettascale.tech>
#
name: arduino_esp32

on:
  workflow_call:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Set up project
        run: |
          cd $HOME
          export ARDUINO_BASE=$HOME/work/arduino_esp32project/
          export ZENOH_PICO_BASE=$HOME/work/zenoh-pico/zenoh-pico/

          mkdir -p $ARDUINO_BASE
          cd $ARDUINO_BASE
          pio init -b esp32thing_plus -O "-DZ_FEATURE_LINK_BLUETOOTH=1 -DZ_FEATURE_LINK_SERIAL=1" -O "build_flags=-DZENOH_COMPILER_GCC -DZENOH_LOG_DEBUG" -O "lib_ldf_mode=deep+"

          cd $ARDUINO_BASE/lib
          ln -s $ZENOH_PICO_BASE

          cd $ARDUINO_BASE

      - name: Build z_pub example
        run: |
          cd $HOME
          export ARDUINO_BASE=$HOME/work/arduino_esp32project/
          export ZENOH_PICO_BASE=$HOME/work/zenoh-pico/zenoh-pico/

          rm -rf $ARDUINO_BASE/src/*
          cd $ARDUINO_BASE/src
          ln -s $ZENOH_PICO_BASE/examples/arduino/z_pub.ino

          cd $ARDUINO_BASE
          pio run

      - name: Build z_sub example
        run: |
          cd $HOME
          export ARDUINO_BASE=$HOME/work/arduino_esp32project/
          export ZENOH_PICO_BASE=$HOME/work/zenoh-pico/zenoh-pico/

          rm -rf $ARDUINO_BASE/src/*
          cd $ARDUINO_BASE/src
          ln -s $ZENOH_PICO_BASE/examples/arduino/z_sub.ino

          cd $ARDUINO_BASE
          pio run

      - name: Build z_pull example
        run: |
          cd $HOME
          export ARDUINO_BASE=$HOME/work/arduino_esp32project/
          export ZENOH_PICO_BASE=$HOME/work/zenoh-pico/zenoh-pico/

          rm -rf $ARDUINO_BASE/src/*
          cd $ARDUINO_BASE/src
          ln -s $ZENOH_PICO_BASE/examples/arduino/z_pull.ino

          cd $ARDUINO_BASE
          pio run

      - name: Build z_get example
        run: |
          cd $HOME
          export ARDUINO_BASE=$HOME/work/arduino_esp32project/
          export ZENOH_PICO_BASE=$HOME/work/zenoh-pico/zenoh-pico/

          rm -rf $ARDUINO_BASE/src/*
          cd $ARDUINO_BASE/src
          ln -s $ZENOH_PICO_BASE/examples/arduino/z_get.ino

          cd $ARDUINO_BASE
          pio run

      - name: Build z_queryable example
        run: |
          cd $HOME
          export ARDUINO_BASE=$HOME/work/arduino_esp32project/
          export ZENOH_PICO_BASE=$HOME/work/zenoh-pico/zenoh-pico/

          rm -rf $ARDUINO_BASE/src/*
          cd $ARDUINO_BASE/src
          ln -s $ZENOH_PICO_BASE/examples/arduino/z_queryable.ino

          cd $ARDUINO_BASE
          pio run

      - name: Build z_scout example
        run: |
          cd $HOME
          export ARDUINO_BASE=$HOME/work/arduino_esp32project/
          export ZENOH_PICO_BASE=$HOME/work/zenoh-pico/zenoh-pico/

          rm -rf $ARDUINO_BASE/src/*
          cd $ARDUINO_BASE/src
          ln -s $ZENOH_PICO_BASE/examples/arduino/z_scout.ino

          cd $ARDUINO_BASE
          pio run
