#
# Copyright (c) 2022 ZettaScale Technology
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0, or the Apache License, Version 2.0
# which is available at https://www.apache.org/licenses/LICENSE-2.0.
#
# SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
#
# Contributors:
#   ZettaScale Zenoh Team, <zenoh@zettascale.tech>
#
name: mbed

on:
  workflow_call:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Set up project
        run: |
          cd $HOME
          export MBED_BASE=$HOME/work/mbedproject/
          export ZENOH_PICO_BASE=$HOME/work/zenoh-pico/zenoh-pico/

          mkdir -p $MBED_BASE
          cd $MBED_BASE
          pio init -b nucleo_f767zi --project-option="framework=mbed" --project-option="board_build.cmake_extra_args=-DZ_FEATURE_LINK_SERIAL=1" -O "build_flags=-DZENOH_COMPILER_GCC -DZENOH_LOG_DEBUG"

          cd $MBED_BASE/lib
          ln -s $ZENOH_PICO_BASE

          cd $MBED_BASE

      - name: Build z_pub example
        run: |
          cd $HOME
          export MBED_BASE=$HOME/work/mbedproject/
          export ZENOH_PICO_BASE=$HOME/work/zenoh-pico/zenoh-pico/

          rm -rf $MBED_BASE/src/*
          cd $MBED_BASE/src
          ln -s $ZENOH_PICO_BASE/examples/mbed/z_pub.cpp

          cd $MBED_BASE
          pio run

      - name: Build z_sub example
        run: |
          cd $HOME
          export MBED_BASE=$HOME/work/mbedproject/
          export ZENOH_PICO_BASE=$HOME/work/zenoh-pico/zenoh-pico/

          rm -rf $MBED_BASE/src/*
          cd $MBED_BASE/src
          ln -s $ZENOH_PICO_BASE/examples/mbed/z_sub.cpp

          cd $MBED_BASE
          pio run

      - name: Build z_pull example
        run: |
          cd $HOME
          export MBED_BASE=$HOME/work/mbedproject/
          export ZENOH_PICO_BASE=$HOME/work/zenoh-pico/zenoh-pico/

          rm -rf $MBED_BASE/src/*
          cd $MBED_BASE/src
          ln -s $ZENOH_PICO_BASE/examples/mbed/z_pull.cpp

          cd $MBED_BASE
          pio run

      - name: Build z_get example
        run: |
          cd $HOME
          export MBED_BASE=$HOME/work/mbedproject/
          export ZENOH_PICO_BASE=$HOME/work/zenoh-pico/zenoh-pico/

          rm -rf $MBED_BASE/src/*
          cd $MBED_BASE/src
          ln -s $ZENOH_PICO_BASE/examples/mbed/z_get.cpp

          cd $MBED_BASE
          pio run

      - name: Build z_queryable example
        run: |
          cd $HOME
          export MBED_BASE=$HOME/work/mbedproject/
          export ZENOH_PICO_BASE=$HOME/work/zenoh-pico/zenoh-pico/

          rm -rf $MBED_BASE/src/*
          cd $MBED_BASE/src
          ln -s $ZENOH_PICO_BASE/examples/mbed/z_queryable.cpp

          cd $MBED_BASE
          pio run

      - name: Build z_scout example
        run: |
          cd $HOME
          export MBED_BASE=$HOME/work/mbedproject/
          export ZENOH_PICO_BASE=$HOME/work/zenoh-pico/zenoh-pico/

          rm -rf $MBED_BASE/src/*
          cd $MBED_BASE/src
          ln -s $ZENOH_PICO_BASE/examples/mbed/z_scout.cpp

          cd $MBED_BASE
          pio run
